export const reviewItems = [
  {
    id: 1,
    title: "선생님 토끼의 실전 자바",
    content: "각 모듈마다 퀴즈와 프로젝트가 있어 배운 내용을 바로 적용할 수 있어 좋았습니다.",
    rating: 5,
    date: "2024.01.11",
    likes: 26,
  },
  {
    id: 2,
    title: "모바일 프로그래밍",
    content: "프로그래밍 초보도 쉽게 따라올 수 있는 훌륭한 강의였습니다.",
    rating: 4,
    date: "2024.01.05",
    likes: 18,
  },
  {
    id: 3,
    title: "데이터베이스 개론",
    content: "복잡한 개념을 쉽게 풀어서 설명해 주셔서 이해가 쉬웠습니다.",
    rating: 5,
    date: "2024.01.03",
    likes: 32,
  },
  {
    id: 4,
    title: "선형대수의 기초",
    content: "수학을 어려워하는 사람도 이해할 수 있는 설명으로 구성된 강의입니다.",
    rating: 4,
    date: "2023.12.29",
    likes: 15,
  },
  {
    id: 5,
    title: "웹 개발 마스터하기",
    content: "HTML, CSS, JavaScript를 한 번에 배울 수 있는 최고의 강의였습니다.",
    rating: 5,
    date: "2023.12.25",
    likes: 40,
  },
  {
    id: 6,
    title: "Python 기초",
    content: "기초부터 차근차근 배울 수 있어 초보자에게 딱 맞는 강의였습니다.",
    rating: 4,
    date: "2023.12.20",
    likes: 22,
  },
  {
    id: 7,
    title: "React 완벽 가이드",
    content: "컴포넌트와 상태 관리에 대한 이해가 확실히 되었습니다.",
    rating: 5,
    date: "2023.12.15",
    likes: 36,
  },
  {
    id: 8,
    title: "Node.js 심화",
    content: "백엔드 개발에 꼭 필요한 내용을 깊이 있게 다룬 강의였습니다.",
    rating: 5,
    date: "2023.12.10",
    likes: 20,
  },
  {
    id: 9,
    title: "AI와 머신러닝",
    content: "기초적인 머신러닝 개념을 이해하기 쉽게 풀어준 강의입니다.",
    rating: 4,
    date: "2023.12.05",
    likes: 17,
  },
  {
    id: 10,
    title: "알고리즘 문제 해결",
    content: "문제 해결 능력을 키울 수 있는 다양한 예제가 포함되어 있습니다.",
    rating: 5,
    date: "2023.12.01",
    likes: 28,
  },
  {
    id: 11,
    title: "Git과 협업",
    content: "협업 도구로서 Git의 활용법을 상세히 알려줍니다.",
    rating: 4,
    date: "2023.11.28",
    likes: 14,
  },
  {
    id: 12,
    title: "DevOps 기초",
    content: "CI/CD 파이프라인 구축을 실습하며 이해할 수 있었습니다.",
    rating: 5,
    date: "2023.11.22",
    likes: 33,
  },
  {
    id: 13,
    title: "Typescript 완전 정복",
    content: "타입 안정성과 코드 품질의 중요성을 느끼게 한 강의입니다.",
    rating: 5,
    date: "2023.11.20",
    likes: 27,
  },
  {
    id: 14,
    title: "Docker와 컨테이너",
    content: "컨테이너 기술의 기본 개념과 실습이 잘 조화를 이룬 강의였습니다.",
    rating: 4,
    date: "2023.11.15",
    likes: 19,
  },
  {
    id: 15,
    title: "JavaScript 심화",
    content: "고급 개념을 실무 예제로 쉽게 설명한 강의였습니다.",
    rating: 5,
    date: "2023.11.10",
    likes: 30,
  },
  {
    id: 16,
    title: "Kubernetes 시작하기",
    content: "초보자를 위한 쿠버네티스 입문 강의로 추천합니다.",
    rating: 4,
    date: "2023.11.05",
    likes: 12,
  },
  {
    id: 17,
    title: "컴퓨터 네트워크 기본",
    content: "네트워크의 기본 개념을 쉽게 이해할 수 있는 강의였습니다.",
    rating: 4,
    date: "2023.11.01",
    likes: 10,
  },
  {
    id: 18,
    title: "안드로이드 프로그래밍",
    content: "모바일 앱 개발의 기초를 탄탄히 다질 수 있었습니다.",
    rating: 5,
    date: "2023.10.28",
    likes: 21,
  },
  {
    id: 19,
    title: "SQL 데이터 분석",
    content: "데이터베이스와 SQL 활용법을 자세히 배울 수 있었습니다.",
    rating: 5,
    date: "2023.10.25",
    likes: 34,
  },
  {
    id: 20,
    title: "클라우드 컴퓨팅",
    content: "AWS를 중심으로 클라우드 기술의 기초를 익힐 수 있었습니다.",
    rating: 4,
    date: "2023.10.20",
    likes: 16,
  },
  {
    id: 21,
    title: "웹 보안 기초",
    content: "웹 애플리케이션 보안의 기초적인 개념을 배울 수 있는 강의였습니다.",
    rating: 5,
    date: "2023.10.18",
    likes: 25,
  },
  {
    id: 22,
    title: "C++ 프로그래밍",
    content: "기초부터 고급 개념까지 차근차근 설명한 강의였습니다.",
    rating: 4,
    date: "2023.10.15",
    likes: 19,
  },
  {
    id: 23,
    title: "블록체인 기술",
    content: "블록체인의 기본 개념을 실습을 통해 익힐 수 있었습니다.",
    rating: 5,
    date: "2023.10.12",
    likes: 27,
  },
  {
    id: 24,
    title: "모바일 게임 개발",
    content: "게임 개발에 필요한 기초를 쉽게 배울 수 있는 강의였습니다.",
    rating: 5,
    date: "2023.10.10",
    likes: 32,
  },
  {
    id: 25,
    title: "자바스크립트 함수형 프로그래밍",
    content: "함수형 프로그래밍을 자바스크립트로 구현하는 방법을 배웠습니다.",
    rating: 4,
    date: "2023.10.05",
    likes: 22,
  },
  {
    id: 26,
    title: "자바 고급 프로그래밍",
    content: "객체 지향과 함수형 프로그래밍을 결합하여 강의가 진행되었습니다.",
    rating: 5,
    date: "2023.09.30",
    likes: 35,
  },
  {
    id: 27,
    title: "게임 디자인",
    content: "게임 개발을 위한 디자인 패턴과 전략을 배울 수 있었습니다.",
    rating: 5,
    date: "2023.09.28",
    likes: 40,
  },
  {
    id: 28,
    title: "머신러닝 기초",
    content: "기계 학습에 대한 기본적인 이해와 실습을 할 수 있었습니다.",
    rating: 4,
    date: "2023.09.25",
    likes: 24,
  },
  {
    id: 29,
    title: "모던 자바스크립트",
    content: "최신 자바스크립트 기능들을 실무 예제로 배운 강의였습니다.",
    rating: 5,
    date: "2023.09.22",
    likes: 28,
  },
  {
    id: 30,
    title: "UI/UX 디자인 입문",
    content: "디자인 이론과 실습을 통해 UI/UX 디자인을 익힐 수 있었습니다.",
    rating: 4,
    date: "2023.09.18",
    likes: 30,
  },
  {
    id: 31,
    title: "디지털 마케팅 전략",
    content: "디지털 마케팅의 기초부터 고급 전략까지 배우는 강의였습니다.",
    rating: 5,
    date: "2023.09.15",
    likes: 18,
  },
  {
    id: 32,
    title: "IoT 개발 입문",
    content: "사물인터넷에 대한 기초적인 이해를 돕는 강의였습니다.",
    rating: 5,
    date: "2023.09.10",
    likes: 21,
  },
  {
    id: 33,
    title: "리눅스 시스템 관리",
    content: "리눅스 시스템을 효과적으로 관리하는 방법을 배울 수 있었습니다.",
    rating: 4,
    date: "2023.09.05",
    likes: 17,
  },
  {
    id: 34,
    title: "React Native 입문",
    content: "모바일 앱 개발을 위한 React Native의 기본을 배운 강의였습니다.",
    rating: 5,
    date: "2023.09.01",
    likes: 29,
  },
  {
    id: 35,
    title: "WebAssembly 기초",
    content: "WebAssembly를 활용한 웹 애플리케이션 성능 향상 기술을 배웠습니다.",
    rating: 4,
    date: "2023.08.29",
    likes: 23,
  },
  {
    id: 36,
    title: "Edge Computing 입문",
    content: "엣지 컴퓨팅의 개념과 활용 사례를 배울 수 있었습니다.",
    rating: 5,
    date: "2023.08.25",
    likes: 20,
  },
  {
    id: 37,
    title: "OpenCV와 컴퓨터 비전",
    content: "OpenCV를 활용한 컴퓨터 비전 기술을 실습할 수 있었습니다.",
    rating: 5,
    date: "2023.08.22",
    likes: 30,
  },
  {
    id: 38,
    title: "AWS 개발 실습",
    content: "AWS를 활용한 클라우드 기반 애플리케이션 개발 실습이 있었습니다.",
    rating: 4,
    date: "2023.08.15",
    likes: 18,
  },
  {
    id: 39,
    title: "게임 프로그래밍 심화",
    content: "고급 게임 프로그래밍 기술을 실습하며 배울 수 있었습니다.",
    rating: 5,
    date: "2023.08.10",
    likes: 34,
  },
  {
    id: 40,
    title: "로보틱스 개론",
    content: "로봇 기술의 기본과 응용을 배울 수 있는 강의였습니다.",
    rating: 5,
    date: "2023.08.05",
    likes: 25,
  }
];
